import { ProductDetail } from '../../pages/products/ProductDetailPage';

export const exampleProducts: ProductDetail[] = [
 {
    id: 1,
    name: 'NVIDIA RTX 4070 Ti',
    price: 3400000,
    imageUrl: '/assets/products/rtx-4070.png',
    isAvailable: true,
    brand: 'NVIDIA',
    description: 'GPU de alto rendimiento con trazado de rayos y DLSS 3. Ideal para gamers y creadores.',
    rating: 4.8,
    reviewCount: 42,
    category: 'Tarjetas Gráficas',
    features: ['12 GB GDDR6X', 'DLSS 3.0', 'Ray Tracing', 'PCIe 4.0'],
    specifications: {
      'Memoria': '12 GB GDDR6X',
      'TDP': '285W',
      'Interfaz': 'PCIe 4.0',
      'Resolución Máxima': '7680x4320',
      'Puertos': 'HDMI 2.1, 3x DisplayPort',
    },
  },
  {
    id: 2,
    name: 'AMD Ryzen 7 5800X',
    price: 999000,
    imageUrl: '/assets/products/ryzen-7.png',
    isAvailable: true,
    brand: 'AMD',
    description: 'Procesador con 8 núcleos y 16 hilos, perfecto para multitarea y juegos exigentes.',
    rating: 4.6,
    reviewCount: 30,
    category: 'Procesadores',
    features: ['8 núcleos', '16 hilos', '4.7GHz Boost', 'AM4 Socket'],
    specifications: {
      'Núcleos': '8',
      'Hilos': '16',
      'Frecuencia Base': '3.8GHz',
      'Frecuencia Máx. Boost': '4.7GHz',
      'Socket': 'AM4',
    },
  },
  {
    id: 3,
    name: 'SSD Samsung 980 PRO 1TB',
    price: 520000,
    imageUrl: '/assets/products/SSD.png',
    isAvailable: false,
    brand: 'Samsung',
    description: 'SSD NVMe ultrarrápido con velocidades de lectura de hasta 7000MB/s.',
    rating: 4.9,
    reviewCount: 58,
    category: 'Almacenamiento',
    features: ['NVMe 4.0', '7000MB/s Lectura', '1000MB/s Escritura', '1TB'],
    specifications: {
      'Capacidad': '1TB',
      'Interfaz': 'NVMe PCIe Gen4',
      'Lectura secuencial': '7000MB/s',
      'Escritura secuencial': '1000MB/s',
    },
  },
];